version: '2'
services:
  db:
    image: mongo
    container_name: db
    restart: always
    expose:
      - "27017"
    networks:
      - net

  bktelegram:
    container_name: bktelegram
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "API_TOKEN=YOUR_API_KEY_HERE"
      - PYTHONUNBUFFERED=0
    ports :
      - "80:80"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - net

networks:
  net:
    driver: bridge